<?php

namespace App\Entity;

use App\Repository\DepenseRepository;
use App\Enum\StatusEnum;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: DepenseRepository::class)]
#[Vich\Uploadable]
class Depense
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: 'datetime_immutable')]
    private ?\DateTimeImmutable $dateDebut = null;

    #[ORM\Column(type: 'date_immutable', nullable: true)]
    private ?\DateTimeImmutable $dateFin = null;

    #[ORM\Column(length: 50)]
    private ?string $typeDepense = null;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: 'decimal', precision: 10, scale: 2)]
    private ?string $montant = null;

    #[ORM\Column(type: 'decimal', precision: 10, scale: 2, nullable: true)]
    private ?string $montantPaye = null;

    #[ORM\Column(type: 'date_immutable', nullable: true)]
    private ?\DateTimeImmutable $dateFacture = null;

    // #[ORM\Column(length: 50)]
    // private ?string $statut = null;

    #[ORM\Column(enumType: StatusEnum::class)]
    private ?StatusEnum $statut = null;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $datePaiement = null;

    #[ORM\ManyToOne(targetEntity: Voiture::class, inversedBy: 'depenses')]
    private ?Voiture $voiture = null;

    #[ORM\ManyToOne(targetEntity: Bureau::class)]
    private ?Bureau $bureau = null;

    #[ORM\ManyToOne(targetEntity: Utilisateur::class)]
    private ?Utilisateur $creePar = null;

    #[ORM\Column(type: 'datetime_immutable')]
    private ?\DateTimeImmutable $creeAu = null;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $editAu = null;

    #[Vich\UploadableField(mapping: 'depense_document', fileNameProperty: 'justificatifName')]
    private ?File $justificatifFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $justificatifName = null;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $deletedAt = null;

    #[ORM\Column]
    private bool $isAutoGenerated = false;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $dismissedAt = null;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $notificationSentAt = null;

    #[ORM\ManyToOne(targetEntity: RecurringExpenseTemplate::class)]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?RecurringExpenseTemplate $recurringTemplate = null;

    #[ORM\Column(nullable: true)]
    private ?int $periodMonth = null;

    #[ORM\Column(nullable: true)]
    private ?int $periodYear = null;

    public function getId(): ?int { return $this->id; }
    public function getDateDebut(): ?\DateTimeImmutable { return $this->dateDebut; }
    public function setDateDebut(\DateTimeImmutable $dateDebut): static { $this->dateDebut = $dateDebut; return $this; }
    public function getDateFin(): ?\DateTimeImmutable { return $this->dateFin; }
    public function setDateFin(?\DateTimeImmutable $dateFin): static { $this->dateFin = $dateFin; return $this; }
    public function getTypeDepense(): ?string { return $this->typeDepense; }
    public function setTypeDepense(string $typeDepense): static { $this->typeDepense = $typeDepense; return $this; }
    public function getDescription(): ?string { return $this->description; }
    public function setDescription(?string $description): static { $this->description = $description; return $this; }
    public function getMontant(): ?string { return $this->montant; }
    public function setMontant(string $montant): static { $this->montant = $montant; return $this; }
    public function getMontantPaye(): ?string { return $this->montantPaye; }
    public function setMontantPaye(?string $montantPaye): static { $this->montantPaye = $montantPaye; return $this; }
    public function getDateFacture(): ?\DateTimeImmutable { return $this->dateFacture; }
    public function setDateFacture(?\DateTimeImmutable $dateFacture): static { $this->dateFacture = $dateFacture; return $this; }
    // public function getStatut(): ?string { return $this->statut; }
    // public function setStatut(string $statut): static { $this->statut = $statut; return $this; }
    public function getStatut(): ?StatusEnum{ return $this->statut; }
    public function setStatut(StatusEnum $statut): static{ $this->statut = $statut;  return $this; }
    public function getDatePaiement(): ?\DateTimeImmutable { return $this->datePaiement; }
    public function setDatePaiement(?\DateTimeImmutable $datePaiement): static { $this->datePaiement = $datePaiement; return $this; }
    public function getVoiture(): ?Voiture { return $this->voiture; }
    public function setVoiture(?Voiture $voiture): static { $this->voiture = $voiture; return $this; }
    public function getBureau(): ?Bureau { return $this->bureau; }
    public function setBureau(?Bureau $bureau): static { $this->bureau = $bureau; return $this; }
    public function getCreePar(): ?Utilisateur { return $this->creePar; }
    public function setCreePar(?Utilisateur $creePar): static { $this->creePar = $creePar; return $this; }
    public function getCreeAu(): ?\DateTimeImmutable { return $this->creeAu; }
    public function setCreeAu(?\DateTimeImmutable $creeAu): static { $this->creeAu = $creeAu; return $this; }
    public function getEditAu(): ?\DateTimeImmutable { return $this->editAu; }
    public function setEditAu(?\DateTimeImmutable $editAu): static { $this->editAu = $editAu; return $this; }
    public function getDeletedAt(): ?\DateTimeImmutable { return $this->deletedAt; }
    public function setDeletedAt(?\DateTimeImmutable $deletedAt): static { $this->deletedAt = $deletedAt; return $this; }

    public function isAutoGenerated(): bool { return $this->isAutoGenerated; }
    public function setIsAutoGenerated(bool $v): static { $this->isAutoGenerated = $v; return $this; }

    public function getDismissedAt(): ?\DateTimeImmutable { return $this->dismissedAt; }
    public function setDismissedAt(?\DateTimeImmutable $v): static { $this->dismissedAt = $v; return $this; }

    public function getNotificationSentAt(): ?\DateTimeImmutable { return $this->notificationSentAt; }
    public function setNotificationSentAt(?\DateTimeImmutable $v): static { $this->notificationSentAt = $v; return $this; }

    public function getRecurringTemplate(): ?RecurringExpenseTemplate { return $this->recurringTemplate; }
    public function setRecurringTemplate(?RecurringExpenseTemplate $t): static { $this->recurringTemplate = $t; return $this; }

    public function getPeriodMonth(): ?int { return $this->periodMonth; }
    public function setPeriodMonth(?int $v): static { $this->periodMonth = $v; return $this; }

    public function getPeriodYear(): ?int { return $this->periodYear; }
    public function setPeriodYear(?int $v): static { $this->periodYear = $v; return $this; }

    public function setJustificatifFile(?File $file = null): void
    {
        $this->justificatifFile = $file;
        if ($file) {
            $this->editAu = new \DateTimeImmutable();
        }
    }
    public function getJustificatifFile(): ?File { return $this->justificatifFile; }
    public function getJustificatifName(): ?string { return $this->justificatifName; }
    public function setJustificatifName(?string $justificatifName): static { $this->justificatifName = $justificatifName; return $this; }
}